from project import convert_weight, convert_volume, convert_currency, convert_length, convert_temperature, get_currency, decide

def test_convert_weight():
    ...

def test_convert_volume():
    ...

def test_convert_currency():
    ...

def test_convert_lenght():
    ...

def test_convert_temperature():
    ...

def test_get_currency():
    ...

def test_decide():
    ...